force-app/main/default/objects/Error_Item__c/Error_Item__c.object-meta.xml
<CustomObject>
    <description>To log exceptions</description>
    <label>Error Item</label>
    <nameField>
        <label>Error Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Error Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Item__c/fields/Error_Description__c.field-meta.xml
<CustomField>
    <fullName>Error_Description__c</fullName>
    <label>Error Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Item__c/fields/Error_Method__c.field-meta.xml
<CustomField>
    <fullName>Error_Method__c</fullName>
    <label>Error Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Item__c/fields/Error_Object__c.field-meta.xml
<CustomField>
    <fullName>Error_Object__c</fullName>
    <label>Error Object</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Item__c/fields/Error_Owner__c.field-meta.xml
<CustomField>
    <fullName>Error_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Error Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Unresolved_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ErrorLogTest.cls
@isTest
public with sharing class ErrorLogTest {
    private static String DESCRIPTION = 'This is a description of the error';
    private static String METHOD = 'Error in queueable';
    private static String ERROR_OBJECT = 'Articles__c';
    private static Id OWNER = UserInfo.getUserId();
    private static String NAME = 'Error when queueing Articles';


    @TestSetup
    static void makeData() {
        ErrorLog.createErrorItem(NAME, ERROR_OBJECT, METHOD, DESCRIPTION, OWNER);
    }

@isTest
static void testErrorItemCreation() {
    // get the Item that was created during the testSetup
    Error_Item__c createdItem = [SELECT Id, Error_Description__c, Error_Method__c, Error_Object__c, Error_Owner__c, Name FROM Error_Item__c];
    
    Assert.areEqual(NAME, createdItem.Name, 'The Name should match');
    Assert.areEqual(ERROR_OBJECT, createdItem.Error_Object__c, 'The object should match');
    Assert.areEqual(METHOD, createdItem.Error_Method__c, 'The Method should match');
    Assert.areEqual(DESCRIPTION, createdItem.Error_Description__c, 'The Description should match');
    Assert.areEqual(OWNER, createdItem.Error_Owner__c, 'The owner should match');
    }
}