force-app/main/default/objects/Error_Item__c/Error_Item__c.object-meta.xml
<CustomObject>
    <description>To log exceptions</description>
    <label>Error Item</label>
    <nameField>
        <label>Error Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Error Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Item__c/fields/Error_Description__c.field-meta.xml
<CustomField>
    <fullName>Error_Description__c</fullName>
    <label>Error Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Item__c/fields/Error_Method__c.field-meta.xml
<CustomField>
    <fullName>Error_Method__c</fullName>
    <label>Error Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Item__c/fields/Error_Object__c.field-meta.xml
<CustomField>
    <fullName>Error_Object__c</fullName>
    <label>Error Object</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Item__c/fields/Error_Owner__c.field-meta.xml
<CustomField>
    <fullName>Error_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Error Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Unresolved_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ErrorLog.cls
public with sharing class ErrorLog {
    
    public static void  createErrorItem(String itemName, String obj, String method, String description, Id ownerId) {
        description = description.length() > 131072 ? description.substring(0, 131072) : description;
        Error_Item__c item = new Error_Item__c(
            Name = itemName,
            Error_Object__c = obj,
            Error_Method__c = method,
            Error_Description__c = description,
            Error_Owner__c = ownerId
        );
        insert item;
    }
    public static void debugException(Exception e) {
        System.debug(LoggingLevel.ERROR, '*** Exception occured!!***');
        System.debug(LoggingLevel.ERROR,'Exception Type caught: ' + e.getTypeName());
        System.debug(LoggingLevel.ERROR,'Message: ' + e.getMessage());
        System.debug(LoggingLevel.ERROR,'Cause: ' + e.getCause());
        System.debug(LoggingLevel.ERROR,'Line Number: ' + e.getLineNumber());
        System.debug(LoggingLevel.ERROR,'Stack trace: ' + e.getStackTraceString());
    }
}